"""index url token

Revision ID: 11e6e8b27b43
Revises: ccdfed38a9e4
Create Date: 2020-09-08 22:10:31.284651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e6e8b27b43'
down_revision = 'ccdfed38a9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_URL_token'), 'URL', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_token'), table_name='URL')
    # ### end Alembic commands ###
