"""add category column

Revision ID: 570bf5a57b76
Revises: aadd5bfa88ce
Create Date: 2020-09-08 17:03:49.518372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570bf5a57b76'
down_revision = 'aadd5bfa88ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('category', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea', 'category')
    # ### end Alembic commands ###
